title: Gestor Tienda Nacho
email: tu-cn.apistock@gmail.com
description: Sistema de Gestión de Tienda Inteligente
baseurl: "" # Déjalo vacío si es el dominio principal
url: "https://tu-usuario.github.io"
markdown: kramdown
