title: Gestor Tienda Nacho
email: cn.apistock@gmail.com
description: Sistema de Gestión de Tienda Inteligente
baseurl: "/GestorTiendaNacho" # Déjalo vacío si es el dominio principal
url: "https://gestorwebtiendanacho.github.io/GestorTiendaNacho/"
markdown: kramdown
